name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 1.8
      uses: actions/setup-java@v5
      with:
        java-version: 1.8
        distribution: zulu

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew -Pversion="" build

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Jars
        path: build/libs/
